version: '3.8'

services:
  db:
    image: postgres:15
    container_name: airbnb_postgres_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: airbnb_redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    container_name: airbnb_django_web
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
