# Generated by Django 5.2.7 on 2025-10-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
