# Generated by Django 5.2.7 on 2025-10-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_propertyimage_options_propertyimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
    ]
